// SPDX-License-Identifier: Apache-2.0

/**
 * TypeScript client generator (spec §31, §32.4). Emits one standalone module
 * per ModDef document containing:
 *
 *  - const-object enums with literal-union types (full type narrowing),
 *  - a per-device `as const` point catalog (the §32.1 metadata view),
 *  - a typed device class per profile wrapping @moddef/core's Device facade
 *    (typed getters/setters per point, spec §26.2 measurand convenience
 *    methods with qualifiers narrowed to what the profile actually has).
 *
 * Output is deterministic (document order, no timestamps) and depends only on
 * @moddef/core.
 */

import { toJson } from "@bufbuild/protobuf";
import { schema } from "@moddef/core";
import { Scope, camel, member, pascal, q } from "./naming.js";

type Doc = schema.ModDefDocument;
type Point = schema.Point;
type DeviceProfile = schema.DeviceProfile;

export interface GeneratedFile {
  /** Suggested file name, e.g. "growatt-sph.ts". */
  path: string;
  content: string;
}

export interface GenerateOptions {
  /** Module specifier for the runtime import (default "@moddef/core"). */
  runtimeModule?: string;
}

export function generate(doc: Doc, opts: GenerateOptions = {}): GeneratedFile[] {
  const runtime = opts.runtimeModule ?? "@moddef/core";
  const g = new Emitter(doc, runtime);
  const base = (doc.docId || "moddef-doc").replace(/[^A-Za-z0-9]+/g, "-");
  return [{ path: `${base}.ts`, content: g.emit() }];
}

// --------------------------------------------------------------------------- //

interface EnumInfo {
  typeName: string; // Pascal type/const name
  members: { name: string; value: number }[];
}

class Emitter {
  private out: string[] = [];
  private enums = new Map<string, EnumInfo>(); // type_id -> info
  private topScope = new Scope();

  constructor(
    private doc: Doc,
    private runtime: string,
  ) {}

  emit(): string {
    this.line(`// Code generated by @moddef/codegen from ${q(this.doc.docId)}; DO NOT EDIT.`);
    this.line(`/* eslint-disable */`);
    this.line(``);
    this.line(`import {`);
    this.line(`  Device,`);
    this.line(`  documentFromJsonValue,`);
    this.line(`  schema,`);
    this.line(`  type DecodedValue,`);
    this.line(`  type Transport,`);
    this.line(`  type TransportOpts,`);
    this.line(`  type Unavailable,`);
    this.line(`} from ${q(this.runtime)};`);
    this.line(``);

    this.emitEnums();
    this.emitDocument();
    for (const dev of this.doc.devices) this.emitDevice(dev);
    return this.out.join("\n") + "\n";
  }

  private line(s: string): void {
    this.out.push(s);
  }

  // ----- enums ------------------------------------------------------------- //

  private emitEnums(): void {
    for (const e of this.doc.enums) {
      const typeName = this.topScope.claim(pascal(e.typeId));
      const seen = new Scope();
      const members = e.values.map((v) => ({
        name: seen.claim(member(v.name)),
        value: Number(v.value),
      }));
      this.enums.set(e.typeId, { typeName, members });

      if (e.description) this.line(`/** ${e.description} */`);
      else if (e.name) this.line(`/** ${e.name} */`);
      this.line(`export const ${typeName} = {`);
      for (const m of members) this.line(`  ${m.name}: ${m.value},`);
      this.line(`} as const;`);
      this.line(
        `export type ${typeName} = (typeof ${typeName})[keyof typeof ${typeName}];`,
      );
      this.line(`export type ${typeName}Name = keyof typeof ${typeName};`);
      this.line(`export function ${camel(e.typeId)}Name(v: ${typeName}): ${typeName}Name {`);
      this.line(`  return (Object.keys(${typeName}) as ${typeName}Name[]).find((k) => ${typeName}[k] === v)!;`);
      this.line(`}`);
      this.line(``);
    }
  }

  // ----- embedded document -------------------------------------------------- //

  private emitDocument(): void {
    const json = JSON.stringify(toJson(schema.ModDefDocumentSchema, this.doc));
    this.line(`const DOC_JSON: unknown = ${json};`);
    this.line(``);
    this.line(`/** The source ModDef document (parsed once at module load). */`);
    this.line(`export const document = documentFromJsonValue(DOC_JSON);`);
    this.line(``);
  }

  // ----- device profile ------------------------------------------------------ //

  private emitDevice(dev: DeviceProfile): void {
    const className = this.topScope.claim(pascal(dev.deviceId));
    const points: Point[] = dev.blocks.flatMap((b) => [...b.points]);

    this.emitCatalog(dev, className, points);

    this.line(`/**`);
    this.line(` * ${dev.vendor} ${dev.model} — typed facade over device profile ${q(dev.deviceId)}.`);
    this.line(` */`);
    this.line(`export class ${className} {`);
    this.line(`  readonly device: Device;`);
    this.line(``);
    this.line(`  constructor(transport: Transport) {`);
    this.line(`    this.device = Device.create(document, ${q(dev.deviceId)}, transport);`);
    this.line(`  }`);

    const methods = new Scope();
    methods.claim("device");

    // Typed per-point accessors.
    for (const p of points) {
      const vt = this.valueTsType(p);
      const readable =
        p.access === schema.AccessMode.READ_ONLY || p.access === schema.AccessMode.READ_WRITE;
      const writable =
        p.access === schema.AccessMode.READ_WRITE ||
        p.access === schema.AccessMode.WRITE_ONLY ||
        p.access === schema.AccessMode.COMMAND;

      if (readable) {
        const name = methods.claim(camel(p.pointId));
        const ret = p.naValues.length > 0 ? `${vt.read} | Unavailable` : vt.read;
        this.line(``);
        if (p.name || p.description) this.line(`  /** ${p.name}${p.description ? ` — ${p.description}` : ""} */`);
        this.line(`  async ${name}(opts?: TransportOpts): Promise<${ret}> {`);
        this.line(
          `    return (await this.device.readPoint(${q(p.pointId)}, opts)) as ${ret};`,
        );
        this.line(`  }`);
      }
      if (writable) {
        const name = methods.claim(`set${pascal(p.pointId)}`);
        this.line(``);
        if (p.name) this.line(`  /** Write ${p.name} (${accessName(p.access)}). */`);
        this.line(`  async ${name}(value: ${vt.write}, opts?: TransportOpts): Promise<void> {`);
        this.line(
          `    await this.device.writePoint(${q(p.pointId)}, value as never, opts);`,
        );
        this.line(`  }`);
      }
    }

    this.emitMeasurandMethods(points, methods);

    this.line(`}`);
    this.line(``);
  }

  // ----- point catalog -------------------------------------------------------- //

  private emitCatalog(dev: DeviceProfile, className: string, points: Point[]): void {
    const catName = this.topScope.claim(`${camel(dev.deviceId)}Points`);
    this.line(`/** Point catalog for device ${q(dev.deviceId)} (spec §32.1 metadata). */`);
    this.line(`export const ${catName} = {`);
    for (const p of points) {
      const m = p.mapping;
      const meas = p.measurand;
      const parts: string[] = [
        `id: ${q(p.pointId)}`,
        `name: ${q(p.name)}`,
        `space: ${q(spaceName(m?.space ?? schema.AddressSpace.ADDRESS_SPACE_UNSPECIFIED))}`,
        `offset: ${m?.offset ?? 0}`,
        `modelRelativeOffset: ${m?.modelRelativeOffset ?? 0}`,
        `lengthWords: ${m?.lengthWords ?? 0}`,
        `storageType: ${q(storageName(p.storageType))}`,
        `access: ${q(accessName(p.access))}`,
        `unit: ${q(p.unit)}`,
      ];
      if (meas?.baseQuantity) {
        parts.push(`baseQuantity: ${q(meas.baseQuantity)}`);
        if (meas.direction) parts.push(`direction: ${q(schema.Direction[meas.direction] ?? "")}`);
        if (meas.phaseRef) parts.push(`phaseRef: ${q(schema.PhaseRef[meas.phaseRef] ?? "")}`);
        if (meas.accumulation) parts.push(`accumulation: ${q(schema.Accumulation[meas.accumulation] ?? "")}`);
        if (meas.aggregation) parts.push(`aggregation: ${q(schema.Aggregation[meas.aggregation] ?? "")}`);
        if (meas.location) parts.push(`location: ${q(schema.MeasurementLocation[meas.location] ?? "")}`);
      }
      this.line(`  ${q(p.pointId)}: { ${parts.join(", ")} },`);
    }
    this.line(`} as const;`);
    this.line(`export type ${className}PointId = keyof typeof ${catName};`);
    this.line(``);
  }

  // ----- measurand convenience (§26.2) ----------------------------------------- //

  private emitMeasurandMethods(points: Point[], methods: Scope): void {
    const byBq = new Map<string, Point[]>();
    for (const p of points) {
      const bq = p.measurand?.baseQuantity;
      if (!bq) continue;
      const list = byBq.get(bq) ?? [];
      list.push(p);
      byBq.set(bq, list);
    }

    for (const [bq, pts] of byBq) {
      const name = methods.claim(`get${pascal(bq)}`);
      const retTypes = [...new Set(pts.map((p) => {
        const t = this.valueTsType(p).read;
        return p.naValues.length > 0 ? `${t} | Unavailable` : t;
      }))];
      const ret = retTypes.join(" | ");

      if (pts.length === 1) {
        this.line(``);
        this.line(`  /** Measurand ${q(bq)} (single matching point: ${pts[0]!.pointId}). */`);
        this.line(`  async ${name}(opts?: TransportOpts): Promise<${ret}> {`);
        this.line(`    return (await this.device.readPoint(${q(pts[0]!.pointId)}, opts)) as ${ret};`);
        this.line(`  }`);
        continue;
      }

      // Which qualifier dimensions actually vary across the matching points?
      const dims: {
        key: string;
        queryKey: string;
        enumName: string;
        names: (p: Point) => string | undefined;
      }[] = [
        { key: "direction", queryKey: "direction", enumName: "Direction", names: (p) => nonZeroName(schema.Direction, p.measurand?.direction) },
        { key: "phase", queryKey: "phaseRef", enumName: "PhaseRef", names: (p) => nonZeroName(schema.PhaseRef, p.measurand?.phaseRef) },
        { key: "accumulation", queryKey: "accumulation", enumName: "Accumulation", names: (p) => nonZeroName(schema.Accumulation, p.measurand?.accumulation) },
        { key: "aggregation", queryKey: "aggregation", enumName: "Aggregation", names: (p) => nonZeroName(schema.Aggregation, p.measurand?.aggregation) },
        { key: "location", queryKey: "location", enumName: "MeasurementLocation", names: (p) => nonZeroName(schema.MeasurementLocation, p.measurand?.location) },
      ];
      const varying = dims
        .map((d) => ({ ...d, values: [...new Set(pts.map(d.names).filter((v): v is string => !!v))].sort() }))
        .filter((d) => d.values.length > 0);

      const params = varying
        .map((d) => `${d.key}?: ${d.values.map((v) => q(v)).join(" | ")}`)
        .join("; ");

      this.line(``);
      this.line(`  /**`);
      this.line(`   * Measurand ${q(bq)} — ${pts.length} matching points; qualify to disambiguate`);
      this.line(`   * (unqualified or under-qualified calls throw AmbiguousMeasurandError, spec §26.4).`);
      this.line(`   */`);
      this.line(`  async ${name}(query: { ${params} } = {}, opts?: TransportOpts): Promise<${ret}> {`);
      this.line(`    return (await this.device.readMeasurand({`);
      this.line(`      baseQuantity: ${q(bq)},`);
      for (const d of varying) {
        this.line(
          `      ${d.queryKey}: query.${d.key} !== undefined ? schema.${d.enumName}[query.${d.key}] : undefined,`,
        );
      }
      this.line(`    }, opts)) as ${ret};`);
      this.line(`  }`);
    }
  }

  // ----- value typing ----------------------------------------------------------- //

  /** TS types for a point's decoded (read) and encodable (write) value. */
  private valueTsType(p: Point): { read: string; write: string } {
    const kind = p.valueType?.kind;

    if (kind?.case === "flags") {
      const names = Object.entries(kind.value.bits)
        .sort(([a], [b]) => Number(a) - Number(b))
        .map(([, n]) => q(n));
      const t = names.length > 0 ? `ReadonlyArray<${names.join(" | ")}>` : "readonly string[]";
      return { read: t, write: t };
    }

    if (p.fields.length > 0 || p.bitFields.length > 0) {
      const fields = [
        ...p.bitFields.map((f) => f.fieldId),
        ...p.fields.map((f) => f.fieldId),
      ];
      const t = `{ ${fields.map((f) => `readonly ${q(f)}: number`).join("; ")} }`;
      return { read: t, write: "never" }; // packed windows are read-modify-write at app level
    }

    if (kind?.case === "enumRef") {
      const info = this.enums.get(kind.value.typeId);
      if (info) return { read: info.typeName, write: info.typeName };
      return { read: "number", write: "number" }; // imported enum: raw value
    }

    const st = p.storageType;
    if (st === schema.StorageType.STRING_ASCII || st === schema.StorageType.STRING_UTF8) {
      return { read: "string", write: "string" };
    }
    if (st === schema.StorageType.BYTES_RAW) return { read: "Uint8Array", write: "Uint8Array" };

    const prim = kind?.case === "primitive" ? kind.value : schema.PrimitiveType.PRIMITIVE_TYPE_UNSPECIFIED;
    switch (prim) {
      case schema.PrimitiveType.BOOL:
        return { read: "boolean", write: "boolean" };
      case schema.PrimitiveType.STRING:
        return { read: "string", write: "string" };
      case schema.PrimitiveType.BYTES:
        return { read: "Uint8Array", write: "Uint8Array" };
      case schema.PrimitiveType.DATETIME:
        return { read: "Date", write: "Date" };
      case schema.PrimitiveType.UINT64:
      case schema.PrimitiveType.INT64:
        return { read: "bigint", write: "bigint" };
      default:
        return { read: "number", write: "number" };
    }
  }
}

function spaceName(s: schema.AddressSpace): string {
  return schema.AddressSpace[s] ?? String(s);
}
function storageName(s: schema.StorageType): string {
  return schema.StorageType[s] ?? String(s);
}
function accessName(a: schema.AccessMode): string {
  return schema.AccessMode[a] ?? String(a);
}
function nonZeroName<E extends Record<string, string | number>>(
  e: E,
  v: number | undefined,
): string | undefined {
  if (!v) return undefined;
  const n = (e as Record<number, string>)[v];
  return typeof n === "string" ? n : undefined;
}
