// SPDX-License-Identifier: Apache-2.0

// ModDef v1 schema — DRAFT until v1.0. See types.proto for the stability policy.
//
// command.proto — multi-step register procedures (commands): typed params,
// ordered linear steps (write / poll / read), and typed results.
// Spec: §11.7 (commands), §11.3 (write behavior), §28.9 (validation).

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file moddef/v1/command.proto (package moddef.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Mapping } from "./mapping_pb.js";
import { file_moddef_v1_mapping } from "./mapping_pb.js";
import type { EnumRef, StorageType, ValueType } from "./types_pb.js";
import { file_moddef_v1_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moddef/v1/command.proto.
 */
export const file_moddef_v1_command: GenFile = /*@__PURE__*/
  fileDesc("Chdtb2RkZWYvdjEvY29tbWFuZC5wcm90bxIJbW9kZGVmLnYxImYKCUNvbmRpdGlvbhIiCgJvcBgBIAEoDjIWLm1vZGRlZi52MS5Db25kaXRpb25PcBINCgV2YWx1ZRgCIAEoAxIMCgRtYXNrGAMgASgDEgsKA21pbhgEIAEoAxILCgNtYXgYBSABKAMiLwoMVHJpZ2dlcldyaXRlEhAKCHBvaW50X2lkGAEgASgJEg0KBXZhbHVlGAIgASgDIlIKCVdyaXRlU3RlcBIPCgVwYXJhbRgBIAEoCUgAEioKB3RyaWdnZXIYAiABKAsyFy5tb2RkZWYudjEuVHJpZ2dlcldyaXRlSABCCAoGdGFyZ2V0ImoKCFBvbGxTdGVwEhAKCHBvaW50X2lkGAEgASgJEiMKBXVudGlsGAIgASgLMhQubW9kZGVmLnYxLkNvbmRpdGlvbhITCgtpbnRlcnZhbF9tcxgDIAEoDRISCgp0aW1lb3V0X21zGAQgASgNIioKCFJlYWRTdGVwEhAKCHBvaW50X2lkGAEgASgJEgwKBGludG8YAiABKAkilAEKC0NvbW1hbmRTdGVwEgwKBG5hbWUYASABKAkSJQoFd3JpdGUYAiABKAsyFC5tb2RkZWYudjEuV3JpdGVTdGVwSAASIwoEcG9sbBgDIAEoCzITLm1vZGRlZi52MS5Qb2xsU3RlcEgAEiMKBHJlYWQYBCABKAsyEy5tb2RkZWYudjEuUmVhZFN0ZXBIAEIGCgRzdGVwIqwBCgxDb21tYW5kUGFyYW0SDQoFZmllbGQYASABKAkSLAoMc3RvcmFnZV90eXBlGAIgASgOMhYubW9kZGVmLnYxLlN0b3JhZ2VUeXBlEigKCnZhbHVlX3R5cGUYAyABKAsyFC5tb2RkZWYudjEuVmFsdWVUeXBlEiMKB21hcHBpbmcYBCABKAsyEi5tb2RkZWYudjEuTWFwcGluZxIQCghyZXF1aXJlZBgFIAEoCCJ8Cg1Db21tYW5kUmVzdWx0Eg0KBWZpZWxkGAEgASgJEgwKBGZyb20YAiABKAkSKAoKdmFsdWVfdHlwZRgDIAEoCzIULm1vZGRlZi52MS5WYWx1ZVR5cGUSJAoIZW51bV9yZWYYBCABKAsyEi5tb2RkZWYudjEuRW51bVJlZiLQAQoHQ29tbWFuZBISCgpjb21tYW5kX2lkGAEgASgJEhMKC2NvbW1hbmRfcmVmGAIgASgJEgwKBG5hbWUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSJwoGcGFyYW1zGAogAygLMhcubW9kZGVmLnYxLkNvbW1hbmRQYXJhbRIlCgVzdGVwcxgUIAMoCzIWLm1vZGRlZi52MS5Db21tYW5kU3RlcBIpCgdyZXN1bHRzGB4gAygLMhgubW9kZGVmLnYxLkNvbW1hbmRSZXN1bHQqUAoLQ29uZGl0aW9uT3ASHAoYQ09ORElUSU9OX09QX1VOU1BFQ0lGSUVEEAASBgoCRVEQARIGCgJORRACEggKBE1BU0sQAxIJCgVSQU5HRRAEQjlaN2dpdGh1Yi5jb20vTW9kRGVmT3JnL21vZGRlZi9nby9nZW5wYi9tb2RkZWYvdjE7bW9kZGVmdjFiBnByb3RvMw", [file_moddef_v1_mapping, file_moddef_v1_types]);

/**
 * §11.7 Exit condition evaluated against the raw (pre-transform) integer
 * value of the polled point. Structural validity per op: MDE507.
 *
 * @generated from message moddef.v1.Condition
 */
export type Condition = Message<"moddef.v1.Condition"> & {
  /**
   * @generated from field: moddef.v1.ConditionOp op = 1;
   */
  op: ConditionOp;

  /**
   * EQ / NE / MASK
   *
   * @generated from field: int64 value = 2;
   */
  value: bigint;

  /**
   * MASK; MUST NOT be zero
   *
   * @generated from field: int64 mask = 3;
   */
  mask: bigint;

  /**
   * RANGE
   *
   * @generated from field: int64 min = 4;
   */
  min: bigint;

  /**
   * RANGE; MUST be >= min
   *
   * @generated from field: int64 max = 5;
   */
  max: bigint;
};

/**
 * Describes the message moddef.v1.Condition.
 * Use `create(ConditionSchema)` to create a new message.
 */
export const ConditionSchema: GenMessage<Condition> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 0);

/**
 * §11.7 Fixed-value write to a point (the "trigger" arming a procedure).
 *
 * @generated from message moddef.v1.TriggerWrite
 */
export type TriggerWrite = Message<"moddef.v1.TriggerWrite"> & {
  /**
   * @generated from field: string point_id = 1;
   */
  pointId: string;

  /**
   * @generated from field: int64 value = 2;
   */
  value: bigint;
};

/**
 * Describes the message moddef.v1.TriggerWrite.
 * Use `create(TriggerWriteSchema)` to create a new message.
 */
export const TriggerWriteSchema: GenMessage<TriggerWrite> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 1);

/**
 * §11.7 One write in a command sequence: either a caller-supplied param
 * (by CommandParam.field) or a fixed trigger value. Step order == wire order.
 *
 * @generated from message moddef.v1.WriteStep
 */
export type WriteStep = Message<"moddef.v1.WriteStep"> & {
  /**
   * @generated from oneof moddef.v1.WriteStep.target
   */
  target: {
    /**
     * @generated from field: string param = 1;
     */
    value: string;
    case: "param";
  } | {
    /**
     * @generated from field: moddef.v1.TriggerWrite trigger = 2;
     */
    value: TriggerWrite;
    case: "trigger";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message moddef.v1.WriteStep.
 * Use `create(WriteStepSchema)` to create a new message.
 */
export const WriteStepSchema: GenMessage<WriteStep> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 2);

/**
 * §11.7 Repeatedly read a point until `until` holds. interval_ms is the
 * pause between reads; timeout_ms bounds the whole step (MDE-level error
 * at runtime on expiry).
 *
 * @generated from message moddef.v1.PollStep
 */
export type PollStep = Message<"moddef.v1.PollStep"> & {
  /**
   * @generated from field: string point_id = 1;
   */
  pointId: string;

  /**
   * @generated from field: moddef.v1.Condition until = 2;
   */
  until?: Condition | undefined;

  /**
   * @generated from field: uint32 interval_ms = 3;
   */
  intervalMs: number;

  /**
   * @generated from field: uint32 timeout_ms = 4;
   */
  timeoutMs: number;
};

/**
 * Describes the message moddef.v1.PollStep.
 * Use `create(PollStepSchema)` to create a new message.
 */
export const PollStepSchema: GenMessage<PollStep> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 3);

/**
 * §11.7 Read a point and bind the decoded value to name `into` for use by
 * a CommandResult. A point whose mapping sets length_ref is read at its
 * runtime-resolved length.
 *
 * @generated from message moddef.v1.ReadStep
 */
export type ReadStep = Message<"moddef.v1.ReadStep"> & {
  /**
   * @generated from field: string point_id = 1;
   */
  pointId: string;

  /**
   * @generated from field: string into = 2;
   */
  into: string;
};

/**
 * Describes the message moddef.v1.ReadStep.
 * Use `create(ReadStepSchema)` to create a new message.
 */
export const ReadStepSchema: GenMessage<ReadStep> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 4);

/**
 * §11.7 One step of a command. Steps execute strictly in order; no branching.
 *
 * @generated from message moddef.v1.CommandStep
 */
export type CommandStep = Message<"moddef.v1.CommandStep"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from oneof moddef.v1.CommandStep.step
   */
  step: {
    /**
     * @generated from field: moddef.v1.WriteStep write = 2;
     */
    value: WriteStep;
    case: "write";
  } | {
    /**
     * @generated from field: moddef.v1.PollStep poll = 3;
     */
    value: PollStep;
    case: "poll";
  } | {
    /**
     * @generated from field: moddef.v1.ReadStep read = 4;
     */
    value: ReadStep;
    case: "read";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message moddef.v1.CommandStep.
 * Use `create(CommandStepSchema)` to create a new message.
 */
export const CommandStepSchema: GenMessage<CommandStep> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 5);

/**
 * §11.7 Caller-supplied input to a command, with its own wire mapping.
 * `required` params MUST be written by at least one WriteStep (MDE504).
 *
 * @generated from message moddef.v1.CommandParam
 */
export type CommandParam = Message<"moddef.v1.CommandParam"> & {
  /**
   * @generated from field: string field = 1;
   */
  field: string;

  /**
   * @generated from field: moddef.v1.StorageType storage_type = 2;
   */
  storageType: StorageType;

  /**
   * @generated from field: moddef.v1.ValueType value_type = 3;
   */
  valueType?: ValueType | undefined;

  /**
   * @generated from field: moddef.v1.Mapping mapping = 4;
   */
  mapping?: Mapping | undefined;

  /**
   * @generated from field: bool required = 5;
   */
  required: boolean;
};

/**
 * Describes the message moddef.v1.CommandParam.
 * Use `create(CommandParamSchema)` to create a new message.
 */
export const CommandParamSchema: GenMessage<CommandParam> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 6);

/**
 * §11.7 One field of a command's result, sourced from a ReadStep binding
 * (`from` names a ReadStep.into or a point_id read after the steps).
 *
 * @generated from message moddef.v1.CommandResult
 */
export type CommandResult = Message<"moddef.v1.CommandResult"> & {
  /**
   * @generated from field: string field = 1;
   */
  field: string;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: moddef.v1.ValueType value_type = 3;
   */
  valueType?: ValueType | undefined;

  /**
   * @generated from field: moddef.v1.EnumRef enum_ref = 4;
   */
  enumRef?: EnumRef | undefined;
};

/**
 * Describes the message moddef.v1.CommandResult.
 * Use `create(CommandResultSchema)` to create a new message.
 */
export const CommandResultSchema: GenMessage<CommandResult> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 7);

/**
 * §11.7 A multi-step register procedure on a device profile. All references
 * (params, point_ids, bindings) resolve within the owning device profile
 * (MDE407/MDE503). command_id MUST be unique per profile (MDE502).
 *
 * @generated from message moddef.v1.Command
 */
export type Command = Message<"moddef.v1.Command"> & {
  /**
   * @generated from field: string command_id = 1;
   */
  commandId: string;

  /**
   * Forward-compat binding to a stdlib command signature (e.g.
   * "stdlib:ocmf-transaction"). Unvalidated until moddef#3.
   *
   * @generated from field: string command_ref = 2;
   */
  commandRef: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: repeated moddef.v1.CommandParam params = 10;
   */
  params: CommandParam[];

  /**
   * @generated from field: repeated moddef.v1.CommandStep steps = 20;
   */
  steps: CommandStep[];

  /**
   * @generated from field: repeated moddef.v1.CommandResult results = 30;
   */
  results: CommandResult[];
};

/**
 * Describes the message moddef.v1.Command.
 * Use `create(CommandSchema)` to create a new message.
 */
export const CommandSchema: GenMessage<Command> = /*@__PURE__*/
  messageDesc(file_moddef_v1_command, 8);

/**
 * §11.7 Comparison operator for a poll-step exit condition.
 *
 * @generated from enum moddef.v1.ConditionOp
 */
export enum ConditionOp {
  /**
   * @generated from enum value: CONDITION_OP_UNSPECIFIED = 0;
   */
  CONDITION_OP_UNSPECIFIED = 0,

  /**
   * raw == value
   *
   * @generated from enum value: EQ = 1;
   */
  EQ = 1,

  /**
   * raw != value
   *
   * @generated from enum value: NE = 2;
   */
  NE = 2,

  /**
   * (raw & mask) == value
   *
   * @generated from enum value: MASK = 3;
   */
  MASK = 3,

  /**
   * min <= raw <= max
   *
   * @generated from enum value: RANGE = 4;
   */
  RANGE = 4,
}

/**
 * Describes the enum moddef.v1.ConditionOp.
 */
export const ConditionOpSchema: GenEnum<ConditionOp> = /*@__PURE__*/
  enumDesc(file_moddef_v1_command, 0);

