// SPDX-License-Identifier: Apache-2.0

// ModDef v1 schema — DRAFT until v1.0. See types.proto for the stability policy.
//
// document.proto — top-level ModDef document and imports.
// Spec: §3 (document model), §6 (structure), §19 (imports/packages).

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file moddef/v1/document.proto (package moddef.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DeviceProfile } from "./device_pb.js";
import { file_moddef_v1_device } from "./device_pb.js";
import type { MeasurandAlias, MeasurandDefinition } from "./measurand_pb.js";
import { file_moddef_v1_measurand } from "./measurand_pb.js";
import type { EnumType, StructType } from "./types_pb.js";
import { file_moddef_v1_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file moddef/v1/document.proto.
 */
export const file_moddef_v1_document: GenFile = /*@__PURE__*/
  fileDesc("Chhtb2RkZWYvdjEvZG9jdW1lbnQucHJvdG8SCW1vZGRlZi52MSLEAgoOTW9kRGVmRG9jdW1lbnQSDgoGZG9jX2lkGAEgASgJEgwKBG5hbWUYAiABKAkSDwoHdmVyc2lvbhgDIAEoCRIiCgdpbXBvcnRzGAQgAygLMhEubW9kZGVmLnYxLkltcG9ydBIiCgVlbnVtcxgKIAMoCzITLm1vZGRlZi52MS5FbnVtVHlwZRImCgdzdHJ1Y3RzGAsgAygLMhUubW9kZGVmLnYxLlN0cnVjdFR5cGUSMgoKbWVhc3VyYW5kcxgMIAMoCzIeLm1vZGRlZi52MS5NZWFzdXJhbmREZWZpbml0aW9uEjQKEW1lYXN1cmFuZF9hbGlhc2VzGA0gAygLMhkubW9kZGVmLnYxLk1lYXN1cmFuZEFsaWFzEikKB2RldmljZXMYFCADKAsyGC5tb2RkZWYudjEuRGV2aWNlUHJvZmlsZSI9CgZJbXBvcnQSCwoDdXJpGAEgASgJEg0KBWFsaWFzGAIgASgJEhcKD2NoZWNrc3VtX3NoYTI1NhgDIAEoCUI5WjdnaXRodWIuY29tL01vZERlZk9yZy9tb2RkZWYvZ28vZ2VucGIvbW9kZGVmL3YxO21vZGRlZnYxYgZwcm90bzM", [file_moddef_v1_device, file_moddef_v1_measurand, file_moddef_v1_types]);

/**
 * §6 A complete ModDef document.
 *
 * @generated from message moddef.v1.ModDefDocument
 */
export type ModDefDocument = Message<"moddef.v1.ModDefDocument"> & {
  /**
   * @generated from field: string doc_id = 1;
   */
  docId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * @generated from field: repeated moddef.v1.Import imports = 4;
   */
  imports: Import[];

  /**
   * @generated from field: repeated moddef.v1.EnumType enums = 10;
   */
  enums: EnumType[];

  /**
   * @generated from field: repeated moddef.v1.StructType structs = 11;
   */
  structs: StructType[];

  /**
   * @generated from field: repeated moddef.v1.MeasurandDefinition measurands = 12;
   */
  measurands: MeasurandDefinition[];

  /**
   * @generated from field: repeated moddef.v1.MeasurandAlias measurand_aliases = 13;
   */
  measurandAliases: MeasurandAlias[];

  /**
   * @generated from field: repeated moddef.v1.DeviceProfile devices = 20;
   */
  devices: DeviceProfile[];
};

/**
 * Describes the message moddef.v1.ModDefDocument.
 * Use `create(ModDefDocumentSchema)` to create a new message.
 */
export const ModDefDocumentSchema: GenMessage<ModDefDocument> = /*@__PURE__*/
  messageDesc(file_moddef_v1_document, 0);

/**
 * §19 Import of an external ModDef document or package.
 *
 * @generated from message moddef.v1.Import
 */
export type Import = Message<"moddef.v1.Import"> & {
  /**
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * @generated from field: string alias = 2;
   */
  alias: string;

  /**
   * @generated from field: string checksum_sha256 = 3;
   */
  checksumSha256: string;
};

/**
 * Describes the message moddef.v1.Import.
 * Use `create(ImportSchema)` to create a new message.
 */
export const ImportSchema: GenMessage<Import> = /*@__PURE__*/
  messageDesc(file_moddef_v1_document, 1);

